# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Naive pattern matching algorithm using C++
#'
#' @description Searches for all occurrences of a pattern in a given text using a brute-force approach.
#' @param texte A character string representing the main text.
#' @param motif A character string representing the pattern to search for.
#' @return A vector of integers indicating the starting positions of each match (1-based index).
naive_pattern_matching_Rcpp <- function(texte, motif) {
    .Call(`_CWRpackage_naive_pattern_matching_Rcpp`, texte, motif)
}

